#!/usr/bin/env python3
"""
Every brief must be true to the ledger, and every rationale must be a pre-match
argument rather than a description of the model or a retrofit of the result.

These checks read the published briefs and picks against fixtures.json:

  briefs      name every scorer, cite every goal minute, run to three
              paragraphs, and never explain how they were produced.
  rationales  cite this tournament rather than a ranking gap, never quote the
              scoreline of the match they precede, and — for the first round,
              where there is no form yet — say so instead of inventing it.

Run: python3 scripts/test_story_facts.py
"""
import json
import os
import re
import sys

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'data')
failures = []


def check(name, cond, detail=''):
    if cond:
        print('  ok  ', name)
    else:
        failures.append(name)
        print('  FAIL', name, '—', detail)


def load(n):
    with open(os.path.join(DATA, n)) as fh:
        return json.load(fh)


def ordinal(n):
    if 10 <= n % 100 <= 20:
        suffix = 'th'
    else:
        suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
    return f'{n}{suffix}'


fixtures = load('fixtures.json')['matches']
stories = {s['matchId']: s for s in load('ai-stories.json')['stories']}
picks = {p['matchId']: p for p in load('predictions.json')['predictions'] if not p.get('superseded')}
done = [m for m in fixtures
        if m['status'] == 'completed' and (m.get('score') or {}).get('home') is not None]
done.sort(key=lambda m: (m['date'], m['time']))

# Whole words only: "development" is not a reference to an Elo model.
PLUMBING = [r'hockey\.ai engine', r'\bledger\b', r'\bpipelines?\b', r'\bthe feed\b',
            r'generated by', r'github actions', r'static json', r'\bapi calls?\b',
            r'\bengine brief\b', r'\belo\b']

print('Briefs against the match record')
check(f'every one of the {len(done)} completed matches has a brief',
      all(m['id'] in stories for m in done),
      ', '.join(m['id'] for m in done if m['id'] not in stories))

for m in done:
    s = stories.get(m['id'])
    if not s:
        continue
    body = s['story']
    low = body.lower()
    goals = [e for e in (m.get('events') or []) if e.get('type') == 'goal']

    missing_names = [g['player'] for g in goals
                     if g.get('player') and g['player'].split()[-1].lower() not in low]
    check(f"{m['id']} names every scorer", not missing_names, ', '.join(missing_names))

    missing_min = [str(g['minute']) for g in goals
                   if ordinal(int(g['minute'])) not in body]
    check(f"{m['id']} cites every goal minute", not missing_min, ", ".join(missing_min))

    check(f"{m['id']} runs to three paragraphs", body.count('\n\n') == 2, str(body.count('\n\n')))
    check(f"{m['id']} is a brief, not a sentence", len(body.split()) >= 120, str(len(body.split())))
    leaked = [w for w in PLUMBING if re.search(w, low)]
    check(f"{m['id']} explains the match, not the machinery", not leaked, ', '.join(leaked))
    check(f"{m['id']} is marked AI-written", s.get('source') == 'ai', str(s.get('source')))

print('\nRationales as pre-match arguments')
seen = set()
for i, m in enumerate(done):
    p = picks.get(m['id'])
    if not p:
        continue
    r = p['reason']
    low = r.lower()

    check(f"{m['id']} argues from more than a ranking gap",
          not re.search(r'fih #\d+ .{0,30}favoured over #\d+', low)
          and not re.search(r'\belo\b', low),
          r[:80])
    # No hindsight: the sentence must not quote the scoreline it precedes.
    score = f"{m['score']['home']}-{m['score']['away']}"
    flip = f"{m['score']['away']}-{m['score']['home']}"
    check(f"{m['id']} does not quote its own result",
          score not in r and flip not in r, f'{score} appears in the rationale')

    first_round = i < 8   # each side's opening match of the tournament
    opener_words = ['no tournament form', 'opening match', 'first match for both',
                    'tournament openers', 'nothing played yet', 'neither side has played',
                    'no form to read', 'opener']
    if first_round:
        check(f"{m['id']} admits there is no form yet",
              any(w in low for w in opener_words), r[:80])
    else:
        # A concrete quantity, in digits or in words — "two wins, eight goals"
        # is evidence; "the better side" is not.
        NUMBERS = r'\d|\b(one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b'
        check(f"{m['id']} cites this tournament",
              bool(re.search(r'\b(scored|conceded|won|points?|corners?|goals?|match(es)?|draw)\b', low))
              and bool(re.search(NUMBERS, low)), r[:80])

    check(f"{m['id']} rationale is a real argument", len(r.split()) >= 25, str(len(r.split())))
    check(f"{m['id']} rationale is unique", r not in seen)
    seen.add(r)

    check(f"{m['id']} keeps what it replaced", bool(p.get('reason_original')))
    check(f"{m['id']} keeps its published pick",
          p.get('pick') in ('HOME', 'DRAW', 'AWAY') and 'publishedAt' in p)

print()
if failures:
    print(f'{len(failures)} check(s) FAILED: {", ".join(failures[:8])}')
    sys.exit(1)
print('All story and rationale checks passed.')
